services:
  - type: web
    name: traffic-study-app
    env: python
    buildCommand: |
      npm install
      npm run build
      pip install -r requirements_production.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
      - key: FLASK_ENV
        value: production
      - key: USE_CLOUDINARY
        value: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: traffic-study-db
          property: connectionString

databases:
  - name: traffic-study-db
    databaseName: traffic_study_app
    user: traffic_user